sudo: required
dist: xenial
language: python
services:
  - docker
python:
  - "3.6"
  - "3.7"
env:
  - TORCH_VERSION=1.0.0 DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda101
before_install:
  - docker pull $DOCKER_IMAGE_NAME
  - docker run --rm -d --name warpctc_builder_container -v ${PWD}:${PWD} -w ${PWD} $DOCKER_IMAGE_NAME sleep inf
install:
  - docker exec -e PYTHON_VERSION=$TRAVIS_PYTHON_VERSION warpctc_builder_container /bin/bash -cl \
    'conda create -q -n test-environment python=$PYTHON_VERSION pytest pytest-pep8'
  - docker exec -e TORCH_VERSION=$TORCH_VERSION warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && conda install pytorch==$TORCH_VERSION torchvision -c pytorch'
  # Useful for debugging any issues with conda
  - docker exec warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && conda info -a'

  - docker exec warpctc_builder_container /bin/bash -cl \
    'mkdir build && cd build && cmake .. && make && make install && ldconfig'
  - docker exec warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && cd pytorch_binding && python setup.py install && ldconfig'

script:
  - docker exec warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && cd pytorch_binding && py.test tests'
  - docker exec warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && cd pytorch_binding && py.test --pep8 -m pep8 --ignore=warpctc_pytorch/_warp_ctc'
  - docker exec warpctc_builder_container /bin/bash -cl \
    'source activate test-environment && cd pytorch_binding && python setup.py bdist_wheel'
  - docker exec warpctc_builder_container /bin/bash -cl \
    'ls -1 pytorch_binding/dist/*.whl | awk "{print \"mv \"\$1\" \"\$1}" | sed "s/-linux_/-manylinux1_/2" | bash'

after_script:
  - docker stop warpctc_builder_container
