sudo: required
dist: xenial
language: python
services:
  - docker
env:
  matrix:
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda92 PYTHON_VERSION=3.6.12 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda92 PYTHON_VERSION=3.7.9 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda92 PYTHON_VERSION=3.8.5 TORCH_VERSIONS=1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda100 PYTHON_VERSION=3.6.12 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda100 PYTHON_VERSION=3.7.9 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda100 PYTHON_VERSION=3.8.5 TORCH_VERSIONS=1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda101 PYTHON_VERSION=3.6.12 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda101 PYTHON_VERSION=3.7.9 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cuda101 PYTHON_VERSION=3.8.5 TORCH_VERSIONS=1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cpu PYTHON_VERSION=3.6.12 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cpu PYTHON_VERSION=3.7.9 TORCH_VERSIONS=1.1.0:1.2.0:1.3.1:1.4.0:1.5.1:1.6.0
    - DOCKER_IMAGE_NAME=espnet/warpctc_builder:cpu PYTHON_VERSION=3.8.5 TORCH_VERSIONS=1.4.0:1.5.1:1.6.0
  global:
    - secure: "P5iuxWY7zhu2lSXjRAikAWNDIwATrQl40TqO6z2dA2E0jBDPoewpLra6lqBDu715Tc+yFDaf/fpfKlM7sn02HGKRnapQB5N9YwI03M5AYTEQS9NvKK603LmRlpQbJZwKCzs0blgcawHmoeFjnFoz0zToWyR+kIYJvUr17T8LWNimcHTv8tVks2bnEOJYEqZKHajz1ORSQ67oV18xx755OP5w71lA0YF/Dh7bGpSamOUkUAOuCva8LKdJwM2w+r4tfhWXZDWpcgFh2WE2qPnmSkPq6jjNZJxAs//2Bn3zi3VhXjs+njuPi+cjvEfbwriVo9iwvK2OlXjygCbY3Sw8a2IeSHccEiaUgG/Ub1g3qsVn2pG6QT6xOQSAbsplPMUJBrrHZfEAxZ8uAAQ9ZkOst2TG+5lEf+0eqRDG6LXiuj2TiRGeXeUIup0MlTbPWvR9tN/aRVHuiGmGKtcklEpICM6tDK0RKlLJ5YYhx4CBXG3EpD/91hFtvhg/7y7RxZmJ+yTXD8b5CtnQdgbt86jZENsRlh/HfIAwiwosElL/ihcMLpTo/v+9ixpSCeiVxjHao3LAO2NXYyRNg/H22kfy8XDzH5dv1Dz7wQu9Z6r29DOAUDe0pH96ql3B/dfFZF282M4zpfuO4cv+0Fw178i721RKzFI+9j6GahgmUk0ZKvU="
before_install:
  - docker pull $DOCKER_IMAGE_NAME
  - docker run --rm -d --name warpctc_builder_container -v ${PWD}:${PWD} -w ${PWD} $DOCKER_IMAGE_NAME sleep inf
install:
  - docker exec -e PYTHON_VERSION=$PYTHON_VERSION warpctc_builder_container /bin/bash -cl \
    'pyenv global $PYTHON_VERSION'
  - docker exec warpctc_builder_container /bin/bash -cl \
    "pip install -U pip setuptools && pip install numpy pytest pytest-flakes wheel twine"
script:
  - docker exec warpctc_builder_container /bin/bash -cl \
    'mkdir build && cd build && cmake .. && make'
  - docker exec -e TORCH_VERSIONS=$TORCH_VERSIONS warpctc_builder_container /bin/bash -cl \
    'cd pytorch_binding && ./wheel/build_wheels.sh && ls dist'
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker exec -e PYPI_TOKEN=$PYPI_TOKEN warpctc_builder_container /bin/bash -cl \
    'cd pytorch_binding && twine upload --config-file .pypirc -p $PYPI_TOKEN dist/*.whl';
    fi
after_script:
  - docker stop warpctc_builder_container
